### ISSUE TITLE
how does cache work for ec2 runner?

### ISSUE THREAD

**Issue by yangcheng** [amyu/setup-android#250]
I am using https://github.com/machulav/ec2-github-runner 
my understanding is each time it start a new instance with an AMI, so any cache taht is generated will be discard in next run, right?

if i want to enable cache, how to do it?

Thanks

**Comment by amyu** [comment]
Hi @yangcheng 

This Library is an Actions that sets up the Android SDK for SelfHostedRunner, as described in REDAME.

In setup-android, actions/cache is used for cache.
If you can use actions/cache on ec2-github-runner, you can also run cache in setup-android.

I hope you will adopt this Library again when you run it on SelfHostedRunner!
