### ISSUE TITLE
Job summary is always being posted and attached to the workflow run

### ISSUE THREAD

**Issue by dinisnunes1** [amyu/setup-android#27]
**Issue:**
The `setup-android` action is always posting the job summary (attached to the workflow run). This can be useful in some cases, but it also pollutes the workflow page.

Example:
<img width="727" alt="job_summary" src="https://user-images.githubusercontent.com/12532273/224700849-accb0610-ec28-4c2a-9730-580058eee0a1.png">

**Solution:**
Add an optional parameter `job-summary`, and only run renderSummary if this is true (can be true by default).

**Comment by dinisnunes1** [comment]
What do you think @amyu?

**Comment by amyu** [comment]
@dinisnunes1 
It was also an option in actios/gradle!
I think it's a very good suggestion!

**Comment by amyu** [comment]
@dinisnunes1 
Changes have been included in v2 and published.
